{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f82b8dfe740>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Картинки в яндексе","uid":"ff98754a5bf9cee0","parentUid":"293dc63f74e2e5552cbfcacef19ccc83","status":"broken","time":{"start":1659722906027,"stop":1659722906046,"duration":19},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"293dc63f74e2e5552cbfcacef19ccc83"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f82b8aafc70>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Поиск в яндексе","uid":"e3545bd2ec6d4879","parentUid":"6f5a53358873717870007c1a831791d6","status":"broken","time":{"start":1659722906285,"stop":1659722906303,"duration":18},"flaky":true,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"6f5a53358873717870007c1a831791d6"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}