{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5723152d70>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Картинки в яндексе","uid":"8e0495c32f8aaff9","parentUid":"c37788544187907971fad8868ba2b7b1","status":"broken","time":{"start":1659191418119,"stop":1659191418151,"duration":32},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"c37788544187907971fad8868ba2b7b1"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5722e09e40>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Поиск в яндексе","uid":"eac92800ab65ae10","parentUid":"2792c58f8e6b7210449c16a909a88cd5","status":"broken","time":{"start":1659191418401,"stop":1659191418419,"duration":18},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"2792c58f8e6b7210449c16a909a88cd5"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}