{"9214267beedc59fe8c2f8d4f710a67a6":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"a4ec9ca0d56c6061","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/33//#testresult/a4ec9ca0d56c6061","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea7fed6170>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191268197,"stop":1659191268219,"duration":22}},{"uid":"db2ce8f094a32e74","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/31//#testresult/db2ce8f094a32e74","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ddcf2a1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191009401,"stop":1659191009421,"duration":20}}]},"6bc54fbf095856b02ce30f6849fa7bbe":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":2},"items":[{"uid":"a6f75d64911bcb2f","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/33//#testresult/a6f75d64911bcb2f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fea7fb8bb20>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191268520,"stop":1659191268539,"duration":19}},{"uid":"3f611ceee3ba9edd","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/31//#testresult/3f611ceee3ba9edd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ddcbdfb80>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191009672,"stop":1659191009690,"duration":18}}]}}