{"6bc54fbf095856b02ce30f6849fa7bbe":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"3f611ceee3ba9edd","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/31//#testresult/3f611ceee3ba9edd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ddcbdfb80>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191009672,"stop":1659191009690,"duration":18}}]},"9214267beedc59fe8c2f8d4f710a67a6":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"db2ce8f094a32e74","reportUrl":"https://schastev.github.io/2022_07_tensor_test_assignment/31//#testresult/db2ce8f094a32e74","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ddcf2a1d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1659191009401,"stop":1659191009421,"duration":20}}]}}