{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd4481ea710>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Картинки в яндексе","uid":"c71206fe4f3ce831","parentUid":"0aa063d3386fa85f436bd9a633728962","status":"broken","time":{"start":1659258678335,"stop":1659258678355,"duration":20},"flaky":true,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"0aa063d3386fa85f436bd9a633728962"},{"name":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd447e6f280>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Поиск в яндексе","uid":"af5ff71f222815b7","parentUid":"2c65fc3aea25448077ffdb379c9a9eb1","status":"broken","time":{"start":1659258678618,"stop":1659258678636,"duration":18},"flaky":true,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"2c65fc3aea25448077ffdb379c9a9eb1"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}